apiVersion: fusion.storage.openshift.io/v1alpha1
kind: FileSystemClaim
metadata:
  labels:
    app.kubernetes.io/name: openshift-fusion-access-operator
    app.kubernetes.io/managed-by: kustomize
  name: filesystemclaim-sample
spec:
  devices:
    - "/dev/disk/by-id/nvme-Amazon_EC2_NVMe_Instance_Storage_AWS1234567890ABCDEF0"
    - "/dev/disk/by-id/nvme-Amazon_EC2_NVMe_Instance_Storage_AWS1234567890ABCDEF1"
    - "/dev/disk/by-id/nvme-Amazon_EC2_NVMe_Instance_Storage_AWS1234567890ABCDEF2"

